[workspace]
resolver = "3"
members = [
    "serseg",
    "ti-asset-builder",
]

[workspace.package]
authors = [ "ThePinkHacker" ]
license = "GPL-3.0-or-later"
repository = "https://github.thepinkhacker.com/tice-rust"
edition = "2024"

[workspace.lints.rust]
unsafe_code = "deny"

[workspace.dependencies]
anyhow = "1.0.104"
ascii = "1.1.0"
clap = "4.6.7"
env_logger = "0.11.11"
futures = "0.3.34"
image = { version = "0.25.10", default-features = false }
imageproc = { version = "0.27.0", default-features = false }
indexmap = { version = "2.14.2", default-features = false }
log = "0.4.34"
serde = "1.0.229"
serde_test = "1.0.177"
serde_valid = "3.1.2"
serseg = { version = "0.1.0", path = "./serseg" }
tokio = "1.53.1"
toml = "1.1.6"
u24 = "0.6.1"
